package com.corenova.bank.entity;

import com.corenova.bank.enums.AccountStatus;
import com.corenova.bank.enums.AccountType;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * ================================================================
 *  Account – Bank Account Entity
 *
 *  Represents a single bank account linked to a Customer CIF.
 *  One customer can hold multiple accounts across types.
 *
 *  Account number format: CNB-{BranchCode}-{SequentialNo}
 *  Example: 1234567890 (10-digit numeric)
 *
 *  Critical financial fields:
 *    • currentBalance   : Real-time available balance (BigDecimal for precision)
 *    • availableBalance : currentBalance - lien/hold amounts
 *    • minimumBalance   : Minimum Average Balance (MAB) requirement
 *
 *  All balance operations MUST go through AccountService.
 *  Direct entity manipulation bypasses audit logging!
 *
 *  In Finacle, this maps to the CASA (Current And Savings Account) module.
 * ================================================================
 */
@Entity
@Table(
    name = "cbs_accounts",
    indexes = {
        @Index(name = "idx_acc_number",   columnList = "account_number"),
        @Index(name = "idx_acc_customer", columnList = "customer_id"),
        @Index(name = "idx_acc_ifsc",     columnList = "ifsc_code"),
        @Index(name = "idx_acc_status",   columnList = "account_status")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Account extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "account_id")
    private Long accountId;

    // ── Account Identification ───────────────────────────────────

    /**
     * 10-digit account number — globally unique.
     * Generated by AccountNumberGeneratorService at account opening.
     * Format: Branch-Code (4 digits) + Sequential (6 digits)
     */
    @Column(name = "account_number", unique = true, nullable = false, length = 20)
    private String accountNumber;

    @Enumerated(EnumType.STRING)
    @Column(name = "account_type", nullable = false, length = 20)
    private AccountType accountType;

    @Enumerated(EnumType.STRING)
    @Column(name = "account_status", nullable = false, length = 25)
    @Builder.Default
    private AccountStatus accountStatus = AccountStatus.PENDING_ACTIVATION;

    // ── Owner ────────────────────────────────────────────────────

    /** The customer who owns this account (CIF link). */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    @Column(name = "account_holder_name", nullable = false, length = 100)
    private String accountHolderName;

    // ── Financial Fields ─────────────────────────────────────────

    /**
     * Current ledger balance.
     * Uses BigDecimal (never Double/Float) for financial precision.
     * Avoids IEEE 754 floating-point errors (e.g. 0.1 + 0.2 ≠ 0.3).
     */
    @Column(name = "current_balance", nullable = false, precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal currentBalance = BigDecimal.ZERO;

    /**
     * Available balance = currentBalance - hold/lien amount.
     * This is what the customer can actually spend.
     */
    @Column(name = "available_balance", nullable = false, precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal availableBalance = BigDecimal.ZERO;

    /**
     * Minimum Average Balance requirement.
     * If currentBalance falls below this, MAB charges are applied.
     */
    @Column(name = "minimum_balance", precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal minimumBalance = new BigDecimal("1000.00");

    /**
     * Lien / hold amount placed on the account.
     * availableBalance = currentBalance - lienAmount.
     */
    @Column(name = "lien_amount", precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal lienAmount = BigDecimal.ZERO;

    /** Currency code — ISO 4217 (INR, USD, GBP). */
    @Column(name = "currency", length = 3)
    @Builder.Default
    private String currency = "INR";

    // ── Interest ─────────────────────────────────────────────────

    /** Annual interest rate (e.g. 3.50 for 3.5% per annum). */
    @Column(name = "interest_rate", precision = 5, scale = 2)
    private BigDecimal interestRate;

    @Column(name = "last_interest_posted_date")
    private LocalDate lastInterestPostedDate;

    // ── Branch & IFSC ────────────────────────────────────────────

    /** IFSC code = RBI branch identifier (e.g. CNB0MAIN001). */
    @Column(name = "ifsc_code", length = 15)
    private String ifscCode;

    @Column(name = "branch_code", length = 20)
    private String branchCode;

    @Column(name = "branch_name", length = 100)
    private String branchName;

    // ── Dates ────────────────────────────────────────────────────

    @Column(name = "account_open_date", nullable = false)
    private LocalDate accountOpenDate;

    /** Set when account is closed — triggers final interest posting. */
    @Column(name = "account_close_date")
    private LocalDate accountCloseDate;

    @Column(name = "last_transaction_date")
    private LocalDateTime lastTransactionDate;

    @Column(name = "dormant_since_date")
    private LocalDate dormantSinceDate;

    // ── Daily Limits ─────────────────────────────────────────────

    /** Daily transaction limit for this account (configurable per segment). */
    @Column(name = "daily_transaction_limit", precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal dailyTransactionLimit = new BigDecimal("100000.00");

    @Column(name = "daily_amount_used_today", precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal dailyAmountUsedToday = BigDecimal.ZERO;

    // ── Joint Account ────────────────────────────────────────────

    @Column(name = "is_joint_account")
    @Builder.Default
    private Boolean isJointAccount = false;

    @Column(name = "joint_holder_name", length = 100)
    private String jointHolderName;

    // ── Nominee ──────────────────────────────────────────────────

    @Column(name = "nominee_name", length = 100)
    private String nomineeName;

    @Column(name = "nominee_relationship", length = 50)
    private String nomineeRelationship;

    // ── Transactions Relationship ────────────────────────────────

    /**
     * Linked transaction records.
     * ALWAYS use lazy loading — an account can have thousands of transactions.
     * Use TransactionRepository for paginated queries instead.
     */



    // ── Helpers ────────────────────────────────────────────────`──

    /** Checks if account can be debited for the requested amount. */
    public boolean hasSufficientBalance(BigDecimal amount) {
        return availableBalance.compareTo(amount) >= 0;
    }

    /** Checks if account is in a transactable state. */
    public boolean isTransactable() {
        return AccountStatus.ACTIVE.equals(accountStatus);
    }
}
